[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

[profile.default.fmt]
line_length = 120
tab_width = 4

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}", chain = 8453 }

[rpc_endpoints]
base = "${BASE_RPC_URL-https://mainnet.base.org}"
